name: ispect
description: "A package combining Inspector, Talker, and more from pub.dev for efficient project implementation."
version: 1.1.6
homepage: https://github.com/K1yoshiSho/ispect.git
issue_tracker: https://github.com/K1yoshiSho/ispect/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_localizations:
    sdk: flutter

    # Logging
  talker_flutter: ^4.2.2
  talker_dio_logger: ^4.2.2
  talker_bloc_logger: ^4.2.2
  talker_riverpod_logger: ^1.0.2

  # Utils
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0

  # UI
  gap: ^3.0.1
  group_button: ^5.3.4
  auto_size_text: ^3.0.0
  feedback_plus: ^0.1.2

  # Others
  provider: ^6.1.2
  performance: ^0.1.1
  flutter_bloc: ^8.1.5
  flutter_cache_manager: ^3.3.2
  simple_app_cache_manager: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  sizzle_lints: ^2.0.2

flutter:
  generate: true
