name: ispectify
description: Foundation logging system for ISpect toolkit (based on Talker)
version: 4.7.0-dev04
homepage: https://github.com/yelmuratoff/ispect.git
issue_tracker: https://github.com/yelmuratoff/ispect/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.3
  web: ^1.1.1
  collection: ^1.19.1
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
