name: ispectify_ws
description: WebSocket interceptor integration for ISpect toolkit using ws package
version: 4.4.8-dev04
homepage: https://github.com/yelmuratoff/ispect.git
issue_tracker: https://github.com/yelmuratoff/ispect/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependency_overrides:
  ispectify:
    path: ../ispectify

dependencies:
  ws: ^1.0.0
  ispectify: ^4.4.8-dev04

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
