name: ispectify_http
description: HTTP interceptor integration for ISpect toolkit using http_interceptor package
version: 4.7.1
homepage: https://github.com/yelmuratoff/ispect.git
issue_tracker: https://github.com/yelmuratoff/ispect/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependency_overrides:
  ispectify:
    path: ../ispectify

dependencies:
  http: ^1.5.0
  http_interceptor: ^2.0.0
  ispectify: ^4.7.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
