name: ispect_example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependency_overrides:
  ispect:
    path: ../../ispect
  ispectify:
    path: ../../ispectify
  ispectify_http:
    path: ../../ispectify_http
  ispectify_bloc:
    path: ../../ispectify_bloc
  ispectify_dio:
    path: ../../ispectify_dio
  ispectify_ws:
    path: ../../ispectify_ws
  ispectify_db:
    path: ../../ispectify_db

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_localizations:
    sdk: flutter

  dio: ^5.8.0+1
  dio_web_adapter: ^2.1.1
  ws: ^1.0.0
  http: ^1.3.0
  flutter_bloc: ^9.1.0
  http_interceptor: ^2.0.0
  flutter_riverpod: ^2.5.1
  share_plus: ^12.0.0
  open_filex: ^4.7.0
  auto_route:

  # Use local paths through dependency_overrides
  ispect: ^4.6.0
  ispectify_dio: ^4.6.0
  ispectify_http: ^4.6.0
  ispectify_bloc: ^4.6.0
  ispectify_ws: ^4.6.0
  ispectify_db: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  build: ^3.0.2
  auto_route_generator: ^10.2.4

flutter:
  uses-material-design: true
  generate: true

platforms:
  android:
  ios:
  macos:
  linux:
  windows:
  web:
