name: ispectify_bloc
description: BLoC state management integration for ISpect toolkit
version: 4.6.0
homepage: https://github.com/yelmuratoff/ispect.git
issue_tracker: https://github.com/yelmuratoff/ispect/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependency_overrides:
  ispectify:
    path: ../ispectify

dependencies:
  ispectify: ^4.6.0
  bloc: ^9.1.0
  meta: ^1.8.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
