name: ispect
description: Logging and inspector tool for Flutter development and testing
version: 4.7.2
homepage: https://github.com/yelmuratoff/ispect.git
issue_tracker: https://github.com/yelmuratoff/ispect/issues

topics:
  - inspector
  - ispect
  - debug
  - toolkit
  - debug-toolkit

platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:

environment:
  sdk: ">=3.6.0 <4.0.0"

dependency_overrides:
  ispectify:
    path: ../ispectify

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.0
  flutter_localizations:
    sdk: flutter
  meta: ^1.16.0
  collection: ^1.19.0

  # Logging
  ispectify: ^4.7.2

  # Utils
  path_provider: ^2.1.5
  web: ^1.1.1

  # UI
  inspector:
    ^3.1.0
    # git:
    #   url: https://github.com/yelmuratoff/inspector.git
  draggable_panel: ^1.4.2
  super_sliver_list: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
