name: ispect
description: "A package combining Inspector, Talker, and more from pub.dev for efficient project implementation."
version: 2.0.8
homepage: https://github.com/yelmuratoff/ispect.git
issue_tracker: https://github.com/yelmuratoff/ispect/issues

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_localizations:
    sdk: flutter

  meta:
    any

    # Logging
  talker_flutter: ^4.5.2
  talker_dio_logger: ^4.5.2
  talker_http_logger: ^0.1.0-dev.21
  talker_bloc_logger: ^4.5.2

  # Utils
  path_provider: ^2.1.5
  share_plus: ^10.0.1
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2

  # UI
  gap: ^3.0.1
  draggable_panel: ^0.0.5

  # Lints
  # custom_lint: ^0.6.4

  # Others
  dio: ^5.7.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # pyramid_lint: ^2.0.0

flutter:
  generate: true
